#cloud-config
autoinstall:
  version: 1
  locale: es_ES.UTF-8
  keyboard:
    layout: es
  timezone: Europe/Madrid

  identity:
    hostname: amd-desktop
    username: usuario
    # Sustituir por un hash real generado con: openssl passwd -6
    password: "$6$OcY49zgtDZ/jz1hO$eZ62oStyz9TnoTqkYYeEQsKHA2olUs3Zxpoh9w4zBh0NpULEbHS14MM/no8Rvqx2/VOcMK5Lk9Q1tyHvU1Tia/"

  ssh:
    install-server: false

  codecs:
    install: true

  drivers:
    install: true

  updates: security

  packages:
    - curl
    - git
    - gh
    - ubuntu-restricted-addons

  snaps:
    - name: bitwarden
      channel: latest/stable
    - name: code
      channel: latest/stable
      classic: true
