---
- name: Configurar repositorios APT externos locales
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Crear directorio de keyrings APT
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Descargar clave de firma de Google Chrome
      ansible.builtin.get_url:
        url: https://dl.google.com/linux/linux_signing_key.pub
        dest: /etc/apt/keyrings/google-chrome.asc
        owner: root
        group: root
        mode: "0644"

    - name: Configurar repositorio de Google Chrome
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.asc] https://dl.google.com/linux/chrome/deb/ stable main
        filename: google-chrome
        state: present
        update_cache: false

    - name: Descargar clave de firma de Brave
      ansible.builtin.get_url:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
        owner: root
        group: root
        mode: "0644"

    - name: Configurar repositorio de Brave
      ansible.builtin.get_url:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser.sources
        dest: /etc/apt/sources.list.d/brave-browser-release.sources
        owner: root
        group: root
        mode: "0644"
