---
- name: Instalar paquetes Snap locales
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Instalar Bitwarden snap
      community.general.snap:
        name: bitwarden
        state: present

    - name: Instalar Termius snap
      community.general.snap:
        name: termius-app
        channel: latest/stable
        state: present

    - name: Instalar OpenCode snap classic
      community.general.snap:
        name: opencode
        channel: latest/stable
        classic: true
        state: present

    - name: Instalar Visual Studio Code snap classic
      community.general.snap:
        name: code
        classic: true
        state: present
